var annotated_dup =
[
    [ "cxxopts", null, [
      [ "values", null, [
        [ "detail", null, [
          [ "SignedCheck", "structcxxopts_1_1values_1_1detail_1_1_signed_check.html", null ],
          [ "SignedCheck< T, false >", "structcxxopts_1_1values_1_1detail_1_1_signed_check_3_01_t_00_01false_01_4.html", null ],
          [ "SignedCheck< T, true >", "structcxxopts_1_1values_1_1detail_1_1_signed_check_3_01_t_00_01true_01_4.html", null ]
        ] ],
        [ "abstract_value", "classcxxopts_1_1values_1_1abstract__value.html", null ],
        [ "standard_value", "classcxxopts_1_1values_1_1standard__value.html", null ],
        [ "standard_value< bool >", "classcxxopts_1_1values_1_1standard__value_3_01bool_01_4.html", null ],
        [ "type_is_container", "structcxxopts_1_1values_1_1type__is__container.html", null ],
        [ "type_is_container< std::vector< T > >", "structcxxopts_1_1values_1_1type__is__container_3_01std_1_1vector_3_01_t_01_4_01_4.html", null ]
      ] ],
      [ "argument_incorrect_type", "classcxxopts_1_1argument__incorrect__type.html", null ],
      [ "HelpGroupDetails", "structcxxopts_1_1_help_group_details.html", null ],
      [ "HelpOptionDetails", "structcxxopts_1_1_help_option_details.html", null ],
      [ "invalid_option_format_error", "classcxxopts_1_1invalid__option__format__error.html", null ],
      [ "KeyValue", "classcxxopts_1_1_key_value.html", null ],
      [ "missing_argument_exception", "classcxxopts_1_1missing__argument__exception.html", null ],
      [ "Option", "structcxxopts_1_1_option.html", null ],
      [ "option_exists_error", "classcxxopts_1_1option__exists__error.html", null ],
      [ "option_has_no_value_exception", "classcxxopts_1_1option__has__no__value__exception.html", null ],
      [ "option_not_exists_exception", "classcxxopts_1_1option__not__exists__exception.html", null ],
      [ "option_not_has_argument_exception", "classcxxopts_1_1option__not__has__argument__exception.html", null ],
      [ "option_not_present_exception", "classcxxopts_1_1option__not__present__exception.html", null ],
      [ "option_required_exception", "classcxxopts_1_1option__required__exception.html", null ],
      [ "option_requires_argument_exception", "classcxxopts_1_1option__requires__argument__exception.html", null ],
      [ "option_syntax_exception", "classcxxopts_1_1option__syntax__exception.html", null ],
      [ "OptionAdder", "classcxxopts_1_1_option_adder.html", null ],
      [ "OptionDetails", "classcxxopts_1_1_option_details.html", null ],
      [ "OptionException", "classcxxopts_1_1_option_exception.html", null ],
      [ "OptionParseException", "classcxxopts_1_1_option_parse_exception.html", null ],
      [ "OptionParser", "classcxxopts_1_1_option_parser.html", null ],
      [ "Options", "classcxxopts_1_1_options.html", null ],
      [ "OptionSpecException", "classcxxopts_1_1_option_spec_exception.html", null ],
      [ "OptionValue", "classcxxopts_1_1_option_value.html", null ],
      [ "ParseResult", "classcxxopts_1_1_parse_result.html", null ],
      [ "Value", "classcxxopts_1_1_value.html", null ]
    ] ],
    [ "kissfft_utils", null, [
      [ "traits", "structkissfft__utils_1_1traits.html", null ]
    ] ],
    [ "Actogram", "class_actogram.html", null ],
    [ "Adxl362Config", "class_adxl362_config.html", null ],
    [ "BitTagLogTab", "class_bit_tag_log_tab.html", null ],
    [ "Callback", "struct_callback.html", null ],
    [ "ConfigInterface", "class_config_interface.html", null ],
    [ "ConfigTab", "class_config_tab.html", null ],
    [ "DataConfig", "class_data_config.html", null ],
    [ "Demo", "class_demo.html", null ],
    [ "Download", "class_download.html", null ],
    [ "Generator", "class_generator.html", null ],
    [ "Hibernate", "class_hibernate.html", null ],
    [ "JFastFIRFilter", "class_j_fast_f_i_r_filter.html", null ],
    [ "JFilterDesign", "class_j_filter_design.html", null ],
    [ "JSlowFIRFilter", "class_j_slow_f_i_r_filter.html", null ],
    [ "kiss_fastfir_state", "structkiss__fastfir__state.html", null ],
    [ "kiss_fft_cpx", "structkiss__fft__cpx.html", null ],
    [ "kiss_fft_state", "structkiss__fft__state.html", null ],
    [ "kiss_fftr_state", "structkiss__fftr__state.html", null ],
    [ "kissfft", "classkissfft.html", null ],
    [ "LinkAdapt", "class_link_adapt.html", "class_link_adapt" ],
    [ "log_Event", "structlog___event.html", null ],
    [ "MainWindow", "class_main_window.html", null ],
    [ "PBEnumGroup", "class_p_b_enum_group.html", "class_p_b_enum_group" ],
    [ "posdata", "structposdata.html", null ],
    [ "QJFastFIRFilter", "class_q_j_fast_f_i_r_filter.html", null ],
    [ "QJFilterDesign", "class_q_j_filter_design.html", null ],
    [ "QJSlowFIRFilter", "class_q_j_slow_f_i_r_filter.html", null ],
    [ "Schedule", "class_schedule.html", null ],
    [ "Tag", "class_tag.html", null ],
    [ "TagMonitor", "class_tag_monitor.html", null ],
    [ "TickerDateTimeOffset", "class_ticker_date_time_offset.html", null ],
    [ "trigdata", "structtrigdata.html", null ],
    [ "UsbDev", "struct_usb_dev.html", null ]
];