/*
 * Generated from board-customizations.json. Do not edit by hand.
 */

#ifndef BOARD_STANDBY_H
#define BOARD_STANDBY_H

#define BOARD_STANDBY_HAS_CONFIG 1

#define HAS_PULLUPA 1
#define HAS_PULLDWNA 1
#define PULLUPA (PAL_PORT_BIT(PAL_PAD(LINE_MAG_CS)) | \
  PAL_PORT_BIT(PAL_PAD(LINE_LPS_CS)) | \
  PAL_PORT_BIT(PAL_PAD(LINE_FLASH_nCS)))
#define PULLDWNA (PAL_PORT_BIT(PAL_PAD(LINE_WKUP1)) | \
  PAL_PORT_BIT(PAL_PAD(LINE_IMU_TRG_TEST)) | \
  PAL_PORT_BIT(PAL_PAD(LINE_ACCEL_SCK)) | \
  PAL_PORT_BIT(PAL_PAD(LINE_ACCEL_MOSI)) | \
  PAL_PORT_BIT(PAL_PAD(LINE_ACCEL_TRG)) | \
  PAL_PORT_BIT(PAL_PAD(LINE_LPS_MOSI)))

#define HAS_PULLUPB 1
#define HAS_PULLDWNB 1
#define PULLUPB (PAL_PORT_BIT(PAL_PAD(LINE_ACCEL_CS)) | \
  PAL_PORT_BIT(PAL_PAD(LINE_RTC_SDA)) | \
  PAL_PORT_BIT(PAL_PAD(LINE_RTC_SCL)))
#define PULLDWNB (PAL_PORT_BIT(PAL_PAD(LINE_FLASH_SCK)) | \
  PAL_PORT_BIT(PAL_PAD(LINE_FLASH_MOSI)))

#define HAS_PULLUPC 0
#define HAS_PULLDWNC 0
#define PULLUPC 0U
#define PULLDWNC 0U

#endif
