#ifndef SENSORVIZ_SENSORSTREAM_H
#define SENSORVIZ_SENSORSTREAM_H

#include <QColor>
#include <QMap>
#include <QVector>
#include <QString>

// sensorViz has two layers of data:
//
// 1. SqliteLoader reads whatever optional tables exist in the database.
// 2. The UI consumes SensorStream objects and does not care which tag type
//    produced them.
//
// A SensorStream is therefore the main handoff type between file loading and
// plotting. When adding a new sensor, prefer converting its table into a new
// SensorStream id instead of adding tag-specific checks to MainWindow.
struct SensorStream
{
    // Stable programmatic id used by menu actions, transforms, and saved ranges.
    // Examples: "pressure", "activity", "altitude", "activity_lowpass".
    QString id;

    // User-facing axis/menu label and units. Units may be empty.
    QString label;
    QString units;

    // Epoch seconds and corresponding values. Vectors are kept parallel.
    QVector<double> time;
    QVector<double> value;

    // Plot styling. Derived streams are generated by sensorViz rather than read
    // directly from the database; they are drawn slightly heavier.
    QColor color;
    bool derived = false;
};

// Loaded SQLite log plus the streams sensorViz knows how to display. Tag type
// is metadata for the File Info pane; UI features are driven by actual streams.
struct SensorLog
{
    QString path;
    QString tagType;

    // Raw info table values, with large opaque config/info blobs filtered out
    // only when the File Info tab is rendered.
    QMap<QString, QString> info;
    QVector<SensorStream> streams;
};

#endif
