#ifndef CUSTOM_H
#define CUSTOM_H
#include "board.h"

#define FIRMWARE_STRING "BitTagNG, Firmware version 2.0.0"
#define PROTOBUFSIZE 4096
#define RV3028_RTC 1
#define USE_ADXL367 1
#define EXTERNAL_FLASH 1
#define TAG_SHUTDOWN_ENTERS_STANDBY 0
#define TAG_IDLE_SLEEP_MODE SHUTDOWN
#define TAG_CONFIGURED_SLEEP_MODE SHUTDOWN
#define TAG_HIBERNATING_SLEEP_MODE SHUTDOWN
#define TAG_FINISHED_SLEEP_MODE SHUTDOWN
#define TAG_ABORTED_SLEEP_MODE SHUTDOWN
#endif
