/**
 * @file custom.h
 * @brief IMUTagbmm350 variant build constants.
 * @author tag firmware authors
 * @date 2026-07-20
 */

#ifndef CUSTOM_H
#define CUSTOM_H

/** @name Storage and firmware identity
 * External flash sizing, strings, protocol sizing, and feature flags.
 * @{
 */
#define EXT_FLASH_SIZE (1024 * 1024 * 16)

#define FIRMWARE_STRING "IMUTagbmm350, Firmware version 1"
#undef  BOARD_NAME
#define BOARD_NAME "IMUTagbmm350"
#define USE_LPS22HH 1
#define SENSOR_CALIBRATION 1
#define QTMONITOR_VERSION 2.0
#define PROTOBUFSIZE 4096
#define SENSOR_CONSTANTS 1
#define CALIBRATION_CONSTANTS 1
#define USE_STOP1 1
#define STOP1_WAKE_EXTI_GROUP1_MASK (1U << 0)
#define CONFIG_HAS_HIBERNATE 0
#define TAG_STATUS_FIXED_VDD100 330
#define TAG_STORAGE_SPI_DMA_BLOCK_READ 1
#define TAG_STORAGE_SPI_DMA_BLOCK_WRITE 1
/** @} */

/** @name Sensor line aliases and conversion constants
 * Board-level wake lines and sample scale constants used by local code.
 *
 * Maintainer note: this target has no local sensors.c. The IMUTag family
 * devices/sensors code switches from AK09940A to BMM350 through
 * TAG_SENSOR_MAG_BMM350, which is generated by the sensor_mag_bmm350 module in
 * project.mk. Keep the bus swap and BMM350 address here because they describe
 * this breakout wiring, not the generic BMM350 driver.
 * @{
 */
#define LINE_ACCEL_INT LINE_WKUP1
#define ACCEL_CONSTANT 0.976f
#define MAG_CONSTANT 0.01
#define SWAP_I2C 1
#define BMM350_I2C_ADDRESS 0x14U
/** @} */

#endif
