#ifndef CUSTOM_H
#define CUSTOM_H

#define FIRMWARE_STRING "BitTag V6, Firmware version 2"
#define BITTAG_V6 1
#undef  BOARD_NAME
#define BOARD_NAME "BitTag V6"
#define PROTOBUFSIZE 4096
#define TAG_SHUTDOWN_ENTERS_STANDBY 0
#define TAG_IDLE_SLEEP_MODE SHUTDOWN
#define TAG_CONFIGURED_SLEEP_MODE SHUTDOWN
#define TAG_HIBERNATING_SLEEP_MODE SHUTDOWN
#define TAG_FINISHED_SLEEP_MODE SHUTDOWN
#define TAG_ABORTED_SLEEP_MODE SHUTDOWN

#endif
