#include "sqlitelog/internal.h"

#include <cstdint>
#include <sstream>
#include <vector>

#include "imutag_log_format.h"

namespace tagcore::sqlite_log {

// IMUTag blocks carry pressure and magnetometer samples plus a packed ten-sample
// accelerometer/gyroscope payload. The database keeps those rows on an elapsed
// microsecond clock measured from the start of data collection.
//
// Firmware writes one t_DataHeader followed by DATALOG_SAMPLES t_DataLog blocks.
// The current fast download path returns IMUTagRawLog, which carries the whole
// 2048-byte t_DataLog page image in one bounded bytes field. The older
// IMUTagLog protobuf mirrors that page shape with repeated IMUTagLogData
// entries. Each old-format entry has compact raw pressure and magnetometer
// samples, and either:
//
// - the raw_data byte array only, or
// - the entire 128-byte t_DataLog image.
//
// The decoder accepts both forms so the download path can evolve without
// forcing the SQLite writer to know which side emitted the payload.

namespace {

constexpr int kImuSamplesPerBlock = 10;
constexpr int kImuAxesPerSample = 6;
constexpr int kImuBytesPerSample = kImuAxesPerSample * 2;
constexpr int kImuRawDataBytes = kImuSamplesPerBlock * kImuBytesPerSample;
constexpr int kImuDataLogBytes = 128;
constexpr int kImuRawDataOffset = 8;
constexpr int kImuBlocksPerPage = 16;
constexpr int kImuPageBytes = kImuBlocksPerPage * kImuDataLogBytes;

struct ImuBlockView
{
    int32_t pressure_raw;
    int32_t mx_raw;
    int32_t my_raw;
    int32_t mz_raw;
    const uint8_t *raw;
    size_t raw_size;
};

double imuAccelMgPerLsb(Lsm6dsv_ACCEL range)
{
    switch (range) {
    case Lsm6dsv_ACCEL_R2G:
        return 0.061;
    case Lsm6dsv_ACCEL_R4G:
        return 0.122;
    case Lsm6dsv_ACCEL_R8G:
        return 0.244;
    case Lsm6dsv_ACCEL_R16G:
        return 0.488;
    default:
        return 1.0;
    }
}

double imuGyroDpsPerLsb(Lsm6dsv_GYRO range)
{
    switch (range) {
    case Lsm6dsv_GYRO_R125dps:
        return 0.004375;
    case Lsm6dsv_GYRO_R250dps:
        return 0.00875;
    case Lsm6dsv_GYRO_R500dps:
        return 0.0175;
    case Lsm6dsv_GYRO_R1000dps:
        return 0.035;
    case Lsm6dsv_GYRO_R2000dps:
        return 0.07;
    case Lsm6dsv_GYRO_R4000dps:
        return 0.14;
    default:
        return 1.0;
    }
}

double pressureRawToHpa(int32_t pressure_raw)
{
    return pressure_raw * IMUTAG_COMPACT_PRESSURE_HPA_PER_LSB;
}

double magRawToUT(int32_t mag_raw)
{
    return mag_raw * IMUTAG_COMPACT_MAG_UT_PER_LSB;
}

bool hasPressureSample(int32_t pressure_raw)
{
    return pressure_raw != IMUTAG_ENV_SKIP_RAW;
}

bool hasMagSample(int32_t mx_raw, int32_t my_raw, int32_t mz_raw)
{
    return mx_raw != IMUTAG_ENV_SKIP_RAW
        || my_raw != IMUTAG_ENV_SKIP_RAW
        || mz_raw != IMUTAG_ENV_SKIP_RAW;
}

int16_t readLeI16(const uint8_t *p)
{
    const uint16_t value = static_cast<uint16_t>(p[0])
        | (static_cast<uint16_t>(p[1]) << 8);
    return static_cast<int16_t>(value);
}

int dumpIMUTagBlocks(WriterContext &ctx,
                     int32_t epoch,
                     uint32_t raw_millisecond,
                     float temperature,
                     const std::vector<ImuBlockView> &blocks)
{
    if (!ctx.createLogTables()) {
        return -2;
    }

    if (!ctx.config.has_lsm6()) {
        ctx.setLastError("IMUTag SQLite output requires an LSM6 configuration");
        return -2;
    }
    if (ctx.imu == nullptr) {
        ctx.setLastError("IMUTag SQLite output missing decode state");
        return -2;
    }

    const Lsm6dsv_ODR odr = ctx.config.lsm6().odr();
    if (odr == Lsm6dsv_ODR_ODR_UNSPECIFIED || !Lsm6dsv_ODR_IsValid(odr)) {
        ctx.setLastError("IMUTag SQLite output requires a valid IMU ODR");
        return -2;
    }
    const int odr_hz = static_cast<int>(odr);

    /*
     * IMUTag logs are currently decoded on an integer microsecond grid. The
     * supported ODRs divide 1,000,000 cleanly, so this keeps sample and block
     * boundaries exact for the rates generated by the firmware.
     */
    const sqlite3_int64 sample_period_us = 1000000 / odr_hz;
    const sqlite3_int64 block_period_us = sample_period_us * kImuSamplesPerBlock;
    const double accel_scale = imuAccelMgPerLsb(ctx.config.lsm6().accel_rng());
    const double gyro_scale = imuGyroDpsPerLsb(ctx.config.lsm6().gyro_rng());

    Statement header_insert(
        ctx.db,
        "INSERT INTO ImuHeader "
        "(HeaderIndex, StartElapsedUs, Epoch, Millisecond, Flags, Temperature) "
        "VALUES (?, ?, ?, ?, ?, ?)");
    Statement event_insert(
        ctx.db,
        "INSERT INTO ImuEvent (StartElapsedUs, HeaderIndex, Event) VALUES (?, ?, ?)");
    Statement pressure_insert(
        ctx.db,
        "INSERT INTO ImuPressure (ElapsedUs, Pressure) VALUES (?, ?)");
    Statement mag_insert(
        ctx.db,
        "INSERT INTO ImuMag (ElapsedUs, mx, my, mz) VALUES (?, ?, ?, ?)");
    Statement accel_insert(
        ctx.db,
        "INSERT INTO ImuAccel (ElapsedUs, ax, ay, az) VALUES (?, ?, ?, ?)");
    Statement gyro_insert(
        ctx.db,
        "INSERT INTO ImuGyro (ElapsedUs, gx, gy, gz) VALUES (?, ?, ?, ?)");

    if (!header_insert.valid()
        || !event_insert.valid()
        || !pressure_insert.valid()
        || !mag_insert.valid()
        || !accel_insert.valid()
        || !gyro_insert.valid()) {
        ctx.setLastSqliteError("Could not prepare IMUTag log insert");
        return -2;
    }

    /*
     * The header timestamp is absolute, but the high-rate data stream is stored
     * relative to collection start. A RESYNC header starts a new timing segment:
     * the new segment is anchored by the header timestamp, then subsequent data
     * returns to the smooth sample-count clock until the next RESYNC.
     */
    const int header_millisecond =
        static_cast<int>(raw_millisecond & IMUTAG_HEADER_MILLIS_MASK);
    const int header_flags =
        static_cast<int>(raw_millisecond & ~IMUTAG_HEADER_MILLIS_MASK);
    const bool header_resync = (raw_millisecond & IMUTAG_HEADER_RESYNC) != 0;
    const bool header_storage_skip =
        (raw_millisecond & IMUTAG_HEADER_RESYNC_STORAGE_SKIP) != 0;
    const sqlite3_int64 header_epoch_ms =
        static_cast<sqlite3_int64>(epoch) * 1000 + header_millisecond;

    if (!ctx.imu->have_collection_anchor) {
        ctx.imu->collection_anchor_epoch_ms = header_epoch_ms;
        ctx.imu->elapsed_base_us = 0;
        ctx.imu->segment_block_count = 0;
        ctx.imu->have_collection_anchor = true;
    } else if (header_resync) {
        const sqlite3_int64 elapsed_from_anchor_us =
            (header_epoch_ms - ctx.imu->collection_anchor_epoch_ms) * 1000;
        const sqlite3_int64 current_end_us =
            ctx.imu->elapsed_base_us
            + static_cast<sqlite3_int64>(ctx.imu->segment_block_count) * block_period_us;
        /*
         * The resync anchor is only millisecond-resolution. If it rounds below
         * the samples already emitted for the previous segment, round the new
         * segment up to the next expected block boundary so elapsed timestamps
         * remain monotonic.
         */
        ctx.imu->elapsed_base_us =
            elapsed_from_anchor_us > current_end_us ? elapsed_from_anchor_us : current_end_us;
        ctx.imu->segment_block_count = 0;
    }

    const sqlite3_int64 header_start_us =
        ctx.imu->elapsed_base_us
        + static_cast<sqlite3_int64>(ctx.imu->segment_block_count) * block_period_us;
    if (!header_insert.bindInt64(1, static_cast<sqlite3_int64>(ctx.imu->header_count))
        || !header_insert.bindInt64(2, header_start_us)
        || !header_insert.bindInt64(3, epoch)
        || !header_insert.bindInt64(4, header_millisecond)
        || !header_insert.bindInt64(5, header_flags)
        || !header_insert.bindDouble(6, temperature)
        || !header_insert.stepDone()) {
        ctx.setLastSqliteError("IMUTag header insert failed");
        return -2;
    }

    if (header_resync
        && (!event_insert.bindInt64(1, header_start_us)
            || !event_insert.bindInt64(2, static_cast<sqlite3_int64>(ctx.imu->header_count))
            || !event_insert.bindText(3, header_storage_skip ? "RESYNC_STORAGE_SKIP" : "RESYNC")
            || !event_insert.stepDone())) {
        ctx.setLastSqliteError("IMUTag resync event insert failed");
        return -2;
    }
    ctx.imu->header_count++;

    for (const ImuBlockView &block : blocks) {
        const uint8_t *raw = block.raw;
        size_t raw_size = block.raw_size;
        // Firmware-side t_DataLog begins with pressure/mag fields. If the full
        // struct image arrives, skip those fields and decode only raw_data.
        if (raw_size == kImuDataLogBytes) {
            raw += kImuRawDataOffset;
            raw_size -= kImuRawDataOffset;
        }
        if (raw_size != kImuRawDataBytes) {
            std::ostringstream error;
            error << "IMUTag data block has " << block.raw_size
                  << " bytes, expected " << kImuRawDataBytes
                  << " raw bytes or " << kImuDataLogBytes
                  << " t_DataLog bytes";
            ctx.setLastError(error.str());
            return -2;
        }

        // Pressure and magnetometer are sampled once per IMU block, so they use
        // the block start time. Accel/gyro samples are expanded below at the
        // configured IMU sample period.
        const sqlite3_int64 block_start_us =
            ctx.imu->elapsed_base_us
            + static_cast<sqlite3_int64>(ctx.imu->segment_block_count) * block_period_us;

        if (hasPressureSample(block.pressure_raw)) {
            if (!pressure_insert.bindInt64(1, block_start_us)
                || !pressure_insert.bindDouble(2,
                                               pressureRawToHpa(block.pressure_raw))
                || !pressure_insert.stepDone()) {
                ctx.setLastSqliteError("IMUTag pressure insert failed");
                return -2;
            }
        }

        if (hasMagSample(block.mx_raw, block.my_raw, block.mz_raw)) {
            if (!mag_insert.bindInt64(1, block_start_us)
                || !mag_insert.bindDouble(2, magRawToUT(block.mx_raw))
                || !mag_insert.bindDouble(3, magRawToUT(block.my_raw))
                || !mag_insert.bindDouble(4, magRawToUT(block.mz_raw))
                || !mag_insert.stepDone()) {
                ctx.setLastSqliteError("IMUTag magnetometer insert failed");
                return -2;
            }
        }

        for (int sample = 0; sample < kImuSamplesPerBlock; sample++) {
            const uint8_t *p = raw + sample * kImuBytesPerSample;
            const int16_t gx = readLeI16(p);
            const int16_t gy = readLeI16(p + 2);
            const int16_t gz = readLeI16(p + 4);
            const int16_t ax = readLeI16(p + 6);
            const int16_t ay = readLeI16(p + 8);
            const int16_t az = readLeI16(p + 10);
            const sqlite3_int64 sample_elapsed_us =
                block_start_us + sample * sample_period_us;

            if (!accel_insert.bindInt64(1, sample_elapsed_us)
                || !accel_insert.bindDouble(2, ax * accel_scale)
                || !accel_insert.bindDouble(3, ay * accel_scale)
                || !accel_insert.bindDouble(4, az * accel_scale)
                || !accel_insert.stepDone()
                || !gyro_insert.bindInt64(1, sample_elapsed_us)
                || !gyro_insert.bindDouble(2, gx * gyro_scale)
                || !gyro_insert.bindDouble(3, gy * gyro_scale)
                || !gyro_insert.bindDouble(4, gz * gyro_scale)
                || !gyro_insert.stepDone()) {
                ctx.setLastSqliteError("IMUTag IMU sample insert failed");
                return -2;
            }
        }

        ctx.imu->block_count++;
        ctx.imu->segment_block_count++;
    }

    return 1;
}

} // namespace

int dumpIMUTagLog(WriterContext &ctx, const IMUTagLog &log)
{
    std::vector<ImuBlockView> blocks;
    blocks.reserve(static_cast<size_t>(log.data().size()));

    for (auto const &entry : log.data()) {
        const std::string &payload = entry.data();
        blocks.push_back({
            entry.pressure_raw(),
            entry.mx_raw(),
            entry.my_raw(),
            entry.mz_raw(),
            reinterpret_cast<const uint8_t *>(payload.data()),
            payload.size(),
        });
    }

    return dumpIMUTagBlocks(ctx,
                            log.epoch(),
                            static_cast<uint32_t>(log.millisecond()),
                            log.temperature(),
                            blocks);
}

int dumpIMUTagRawLog(WriterContext &ctx, const IMUTagRawLog &log)
{
    const std::string &payload = log.samples();
    if (payload.size() != kImuPageBytes) {
        std::ostringstream error;
        error << "IMUTag raw page has " << payload.size()
              << " bytes, expected " << kImuPageBytes;
        ctx.setLastError(error.str());
        return -2;
    }

    const uint8_t *page = reinterpret_cast<const uint8_t *>(payload.data());
    std::vector<ImuBlockView> blocks;
    blocks.reserve(kImuBlocksPerPage);

    for (int i = 0; i < kImuBlocksPerPage; i++) {
        const uint8_t *block = page + i * kImuDataLogBytes;
        blocks.push_back({
            readLeI16(block),
            readLeI16(block + 2),
            readLeI16(block + 4),
            readLeI16(block + 6),
            block,
            kImuDataLogBytes,
        });
    }

    return dumpIMUTagBlocks(ctx,
                            log.epoch(),
                            static_cast<uint32_t>(log.millisecond()),
                            log.temperature(),
                            blocks);
}

} // namespace tagcore::sqlite_log
