/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TAG_PB_H_INCLUDED
#define PB_TAG_PB_H_INCLUDED
#include <pb.h>
#include "tagdata.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _TestReq {
    TESTS_UNSPECIFIED = 0,
    RUN_ALL = 1,
    RUN_RTC = 2,
    RUN_ADXL362 = 3,
    RUN_LPS = 4,
    RUN_EXT_FLASH = 5,
    RUN_OPT = 6,
    RUN_AIS2 = 7,
    RUN_MMC5633 = 8
} TestReq;

typedef enum _TagState {
    STATE_UNSPECIFIED = 0,
    TEST = 1, /* self test in progress */
    IDLE = 2, /* ready */
    CONFIGURED = 3, /* configured */
    RUNNING = 4, /* actively collecting data */
    HIBERNATING = 5, /* running, but not active */
    ABORTED = 6, /* error, or stop received */
    FINISHED = 7, /* normal termination */
    sRESET = 8, /* reset in progress */
    EXCEPTION = 9, /* unhandled exception */
    CALIBRATE = 10 /* state for calibration of sensors */
} TagState;

typedef enum _Ack_Err {
    Ack_UNSPECIFIED = 0,
    Ack_OK = 1,
    /* Host Error */
    Ack_EMPTY_RETURN = 2, /* return type unexpected */
    Ack_MONITOR = 3, /* reserved for monitor */
    /* Tag Error */
    Ack_NODATA = 4, /* no data */
    Ack_INVAL = 5, /* invalid operand */
    Ack_PERM = 6, /* operation not permitted */
    Ack_NXIO = 7, /* operation failed */
    Ack_NANOPB = 8 /* nanopb error */
} Ack_Err;

typedef enum _LogReq_LogDataType {
    LogReq_LOG_UNSPECIFIED = 0,
    LogReq_SYSTEM_LOG = 1,
    LogReq_INTERNAL_DATA = 2,
    LogReq_EXTERNAL_DATA = 3
} LogReq_LogDataType;

typedef enum _State_Event {
    State_EVENT_UNSPECIFIED = 0,
    State_EVENT_OK = 1,
    State_EVENT_STARTCMD = 2, /* start event */
    State_EVENT_ENDTIM = 3, /* programmed end time */
    State_EVENT_STARTTIM = 4, /* programmed start time */
    State_EVENT_STARTHIB = 5, /* programmed hibernation time */
    State_EVENT_ENDHIB = 6, /* programmed end hibernation time */
    State_EVENT_STOPCMD = 7, /* monitor stop event */
    State_EVENT_RESETCMD = 8, /* reset */
    State_EVENT_LOWBATTERY = 9, /* low battery */
    State_EVENT_INTERNALFULL = 10, /* no more internal data space */
    State_EVENT_EXTERNALFULL = 11, /* no more exteral data space */
    State_EVENT_BROWNOUT = 12, /* brownout event */
    State_EVENT_POWERFAIL = 13, /* power failure */
    State_EVENT_UNKNOWN = 14, /* unknown failure */
    State_EVENT_SLEEP = 15, /* sleep event */
    State_EVENT_STANDBY = 16, /* standby event */
    State_EVENT_SHUTDOWN = 17, /* shutdown event */
    State_EVENT_EXCEPTION = 18 /* exception event */
} State_Event;

/* Struct definitions */
typedef struct _Empty {
    char dummy_field;
} Empty;

typedef struct _LogReq {
    LogReq_LogDataType fmt; /* type of log */
    uint32_t index; /* next index */
} LogReq;

typedef struct _Req {
    pb_size_t which_payload;
    union {
        Empty get_info; /* static tag information */
        Empty get_status; /* current tag status */
        Empty get_config; /* current tag configuration */
        Empty erase; /* erase tag (return to Idle) */
        Config start; /* configure & start tag */
        Empty stop; /* stop tag */
        TestReq test; /* start test */
        int64_t set_rtc; /* set clock (milliseconds) */
        LogReq log;
        Empty calibrate; /* go to sensor calibrate state */
        Empty caldata; /* request calibration log */
        CalibrationConstants write_calibration;
        int32_t read_calibration; /* read index, < 0 means last written, > -1 means specific */
    } payload;
} Req;

typedef struct _Status {
    int64_t millis; /* current time in ms */
    TagState state; /* current state */
    TestResult test_status; /* test result */
    int32_t internal_data_count; /* number of internal data entries */
    int32_t external_data_count; /* number of external data entries */
    float voltage; /* system voltage */
    float temperature; /* processor Temperature */
    int32_t sectors_erased; /* during erase operation provides */
    /* feedback of erased sectors */
    int32_t erase_sectors_total_plus_one;
    /* 0 means unsupported/unknown. Otherwise
 erase sector total is value - 1. */
    char debug_message[128]; /* debug message from buffer */
} Status;

typedef struct _State {
    bool has_status;
    Status status;
    State_Event transition_reason; /* transition event code */
} State;

typedef struct _StateLog {
    pb_size_t states_count;
    State states[10];
} StateLog;

typedef struct _Ack {
    Ack_Err err;
    pb_size_t which_payload;
    union {
        TagInfo info;
        Config config; /* configuration return */
        Status status; /* current status */
        char error_message[64]; /* debugging support */
        StateLog system_log;
        CalibrationLog calibration_log;
        CalibrationConstants calibration_constants;
        IMUTagLog imu_data_log;
        IMUTagRawLog imu_raw_data_log;
    } payload;
} Ack;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _TestReq_MIN TESTS_UNSPECIFIED
#define _TestReq_MAX RUN_MMC5633
#define _TestReq_ARRAYSIZE ((TestReq)(RUN_MMC5633+1))
#define TestReq_TESTS_UNSPECIFIED TESTS_UNSPECIFIED
#define TestReq_RUN_ALL RUN_ALL
#define TestReq_RUN_RTC RUN_RTC
#define TestReq_RUN_ADXL362 RUN_ADXL362
#define TestReq_RUN_LPS RUN_LPS
#define TestReq_RUN_EXT_FLASH RUN_EXT_FLASH
#define TestReq_RUN_OPT RUN_OPT
#define TestReq_RUN_AIS2 RUN_AIS2
#define TestReq_RUN_MMC5633 RUN_MMC5633

#define _TagState_MIN STATE_UNSPECIFIED
#define _TagState_MAX CALIBRATE
#define _TagState_ARRAYSIZE ((TagState)(CALIBRATE+1))
#define TagState_STATE_UNSPECIFIED STATE_UNSPECIFIED
#define TagState_TEST TEST
#define TagState_IDLE IDLE
#define TagState_CONFIGURED CONFIGURED
#define TagState_RUNNING RUNNING
#define TagState_HIBERNATING HIBERNATING
#define TagState_ABORTED ABORTED
#define TagState_FINISHED FINISHED
#define TagState_sRESET sRESET
#define TagState_EXCEPTION EXCEPTION
#define TagState_CALIBRATE CALIBRATE

#define _Ack_Err_MIN Ack_UNSPECIFIED
#define _Ack_Err_MAX Ack_NANOPB
#define _Ack_Err_ARRAYSIZE ((Ack_Err)(Ack_NANOPB+1))
#define Ack_Err_UNSPECIFIED Ack_UNSPECIFIED
#define Ack_Err_OK Ack_OK
#define Ack_Err_EMPTY_RETURN Ack_EMPTY_RETURN
#define Ack_Err_MONITOR Ack_MONITOR
#define Ack_Err_NODATA Ack_NODATA
#define Ack_Err_INVAL Ack_INVAL
#define Ack_Err_PERM Ack_PERM
#define Ack_Err_NXIO Ack_NXIO
#define Ack_Err_NANOPB Ack_NANOPB

#define _LogReq_LogDataType_MIN LogReq_LOG_UNSPECIFIED
#define _LogReq_LogDataType_MAX LogReq_EXTERNAL_DATA
#define _LogReq_LogDataType_ARRAYSIZE ((LogReq_LogDataType)(LogReq_EXTERNAL_DATA+1))
#define LogReq_LogDataType_LOG_UNSPECIFIED LogReq_LOG_UNSPECIFIED
#define LogReq_LogDataType_SYSTEM_LOG LogReq_SYSTEM_LOG
#define LogReq_LogDataType_INTERNAL_DATA LogReq_INTERNAL_DATA
#define LogReq_LogDataType_EXTERNAL_DATA LogReq_EXTERNAL_DATA

#define _State_Event_MIN State_EVENT_UNSPECIFIED
#define _State_Event_MAX State_EVENT_EXCEPTION
#define _State_Event_ARRAYSIZE ((State_Event)(State_EVENT_EXCEPTION+1))
#define State_Event_EVENT_UNSPECIFIED State_EVENT_UNSPECIFIED
#define State_Event_EVENT_OK State_EVENT_OK
#define State_Event_EVENT_STARTCMD State_EVENT_STARTCMD
#define State_Event_EVENT_ENDTIM State_EVENT_ENDTIM
#define State_Event_EVENT_STARTTIM State_EVENT_STARTTIM
#define State_Event_EVENT_STARTHIB State_EVENT_STARTHIB
#define State_Event_EVENT_ENDHIB State_EVENT_ENDHIB
#define State_Event_EVENT_STOPCMD State_EVENT_STOPCMD
#define State_Event_EVENT_RESETCMD State_EVENT_RESETCMD
#define State_Event_EVENT_LOWBATTERY State_EVENT_LOWBATTERY
#define State_Event_EVENT_INTERNALFULL State_EVENT_INTERNALFULL
#define State_Event_EVENT_EXTERNALFULL State_EVENT_EXTERNALFULL
#define State_Event_EVENT_BROWNOUT State_EVENT_BROWNOUT
#define State_Event_EVENT_POWERFAIL State_EVENT_POWERFAIL
#define State_Event_EVENT_UNKNOWN State_EVENT_UNKNOWN
#define State_Event_EVENT_SLEEP State_EVENT_SLEEP
#define State_Event_EVENT_STANDBY State_EVENT_STANDBY
#define State_Event_EVENT_SHUTDOWN State_EVENT_SHUTDOWN
#define State_Event_EVENT_EXCEPTION State_EVENT_EXCEPTION

#define Req_payload_test_ENUMTYPE TestReq

#define Ack_err_ENUMTYPE Ack_Err


#define LogReq_fmt_ENUMTYPE LogReq_LogDataType

#define Status_state_ENUMTYPE TagState
#define Status_test_status_ENUMTYPE TestResult

#define State_transition_reason_ENUMTYPE State_Event



/* Initializer values for message structs */
#define Req_init_default                         {0, {Empty_init_default}}
#define Ack_init_default                         {_Ack_Err_MIN, 0, {TagInfo_init_default}}
#define Empty_init_default                       {0}
#define LogReq_init_default                      {_LogReq_LogDataType_MIN, 0}
#define Status_init_default                      {0, _TagState_MIN, _TestResult_MIN, 0, 0, 0, 0, 0, 0, ""}
#define State_init_default                       {false, Status_init_default, _State_Event_MIN}
#define StateLog_init_default                    {0, {State_init_default, State_init_default, State_init_default, State_init_default, State_init_default, State_init_default, State_init_default, State_init_default, State_init_default, State_init_default}}
#define Req_init_zero                            {0, {Empty_init_zero}}
#define Ack_init_zero                            {_Ack_Err_MIN, 0, {TagInfo_init_zero}}
#define Empty_init_zero                          {0}
#define LogReq_init_zero                         {_LogReq_LogDataType_MIN, 0}
#define Status_init_zero                         {0, _TagState_MIN, _TestResult_MIN, 0, 0, 0, 0, 0, 0, ""}
#define State_init_zero                          {false, Status_init_zero, _State_Event_MIN}
#define StateLog_init_zero                       {0, {State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define LogReq_fmt_tag                           1
#define LogReq_index_tag                         2
#define Req_get_info_tag                         1
#define Req_get_status_tag                       2
#define Req_get_config_tag                       3
#define Req_erase_tag                            4
#define Req_start_tag                            5
#define Req_stop_tag                             6
#define Req_test_tag                             7
#define Req_set_rtc_tag                          8
#define Req_log_tag                              9
#define Req_calibrate_tag                        11
#define Req_caldata_tag                          12
#define Req_write_calibration_tag                13
#define Req_read_calibration_tag                 14
#define Status_millis_tag                        1
#define Status_state_tag                         2
#define Status_test_status_tag                   3
#define Status_internal_data_count_tag           4
#define Status_external_data_count_tag           5
#define Status_voltage_tag                       6
#define Status_temperature_tag                   7
#define Status_sectors_erased_tag                8
#define Status_erase_sectors_total_plus_one_tag  9
#define Status_debug_message_tag                 20
#define State_status_tag                         1
#define State_transition_reason_tag              2
#define StateLog_states_tag                      1
#define Ack_err_tag                              1
#define Ack_info_tag                             2
#define Ack_config_tag                           3
#define Ack_status_tag                           4
#define Ack_error_message_tag                    5
#define Ack_system_log_tag                       6
#define Ack_calibration_log_tag                  13
#define Ack_calibration_constants_tag            14
#define Ack_imu_data_log_tag                     15
#define Ack_imu_raw_data_log_tag                 16

/* Struct field encoding specification for nanopb */
#define Req_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,get_info,payload.get_info),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,get_status,payload.get_status),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,get_config,payload.get_config),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,erase,payload.erase),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,start,payload.start),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,stop,payload.stop),   6) \
X(a, STATIC,   ONEOF,    UENUM,    (payload,test,payload.test),   7) \
X(a, STATIC,   ONEOF,    INT64,    (payload,set_rtc,payload.set_rtc),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,log,payload.log),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,calibrate,payload.calibrate),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,caldata,payload.caldata),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,write_calibration,payload.write_calibration),  13) \
X(a, STATIC,   ONEOF,    INT32,    (payload,read_calibration,payload.read_calibration),  14)
#define Req_CALLBACK NULL
#define Req_DEFAULT NULL
#define Req_payload_get_info_MSGTYPE Empty
#define Req_payload_get_status_MSGTYPE Empty
#define Req_payload_get_config_MSGTYPE Empty
#define Req_payload_erase_MSGTYPE Empty
#define Req_payload_start_MSGTYPE Config
#define Req_payload_stop_MSGTYPE Empty
#define Req_payload_log_MSGTYPE LogReq
#define Req_payload_calibrate_MSGTYPE Empty
#define Req_payload_caldata_MSGTYPE Empty
#define Req_payload_write_calibration_MSGTYPE CalibrationConstants

#define Ack_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    err,               1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,info,payload.info),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,config,payload.config),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,status,payload.status),   4) \
X(a, STATIC,   ONEOF,    STRING,   (payload,error_message,payload.error_message),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,system_log,payload.system_log),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,calibration_log,payload.calibration_log),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,calibration_constants,payload.calibration_constants),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,imu_data_log,payload.imu_data_log),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,imu_raw_data_log,payload.imu_raw_data_log),  16)
#define Ack_CALLBACK NULL
#define Ack_DEFAULT NULL
#define Ack_payload_info_MSGTYPE TagInfo
#define Ack_payload_config_MSGTYPE Config
#define Ack_payload_status_MSGTYPE Status
#define Ack_payload_system_log_MSGTYPE StateLog
#define Ack_payload_calibration_log_MSGTYPE CalibrationLog
#define Ack_payload_calibration_constants_MSGTYPE CalibrationConstants
#define Ack_payload_imu_data_log_MSGTYPE IMUTagLog
#define Ack_payload_imu_raw_data_log_MSGTYPE IMUTagRawLog

#define Empty_FIELDLIST(X, a) \

#define Empty_CALLBACK NULL
#define Empty_DEFAULT NULL

#define LogReq_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    fmt,               1) \
X(a, STATIC,   SINGULAR, UINT32,   index,             2)
#define LogReq_CALLBACK NULL
#define LogReq_DEFAULT NULL

#define Status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    millis,            1) \
X(a, STATIC,   SINGULAR, UENUM,    state,             2) \
X(a, STATIC,   SINGULAR, UENUM,    test_status,       3) \
X(a, STATIC,   SINGULAR, INT32,    internal_data_count,   4) \
X(a, STATIC,   SINGULAR, INT32,    external_data_count,   5) \
X(a, STATIC,   SINGULAR, FLOAT,    voltage,           6) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       7) \
X(a, STATIC,   SINGULAR, INT32,    sectors_erased,    8) \
X(a, STATIC,   SINGULAR, INT32,    erase_sectors_total_plus_one,   9) \
X(a, STATIC,   SINGULAR, STRING,   debug_message,    20)
#define Status_CALLBACK NULL
#define Status_DEFAULT NULL

#define State_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  status,            1) \
X(a, STATIC,   SINGULAR, UENUM,    transition_reason,   2)
#define State_CALLBACK NULL
#define State_DEFAULT NULL
#define State_status_MSGTYPE Status

#define StateLog_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  states,            1)
#define StateLog_CALLBACK NULL
#define StateLog_DEFAULT NULL
#define StateLog_states_MSGTYPE State

extern const pb_msgdesc_t Req_msg;
extern const pb_msgdesc_t Ack_msg;
extern const pb_msgdesc_t Empty_msg;
extern const pb_msgdesc_t LogReq_msg;
extern const pb_msgdesc_t Status_msg;
extern const pb_msgdesc_t State_msg;
extern const pb_msgdesc_t StateLog_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Req_fields &Req_msg
#define Ack_fields &Ack_msg
#define Empty_fields &Empty_msg
#define LogReq_fields &LogReq_msg
#define Status_fields &Status_msg
#define State_fields &State_msg
#define StateLog_fields &StateLog_msg

/* Maximum encoded size of messages (where known) */
#define Ack_size                                 2736
#define Empty_size                               0
#define LogReq_size                              8
#define Req_size                                 99
#define StateLog_size                            2080
#define State_size                               205
#define Status_size                              200
#define TAG_PB_H_MAX_SIZE                        Ack_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
