/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "tag.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Req, Req, AUTO)


PB_BIND(Ack, Ack, 2)


PB_BIND(Empty, Empty, AUTO)


PB_BIND(LogReq, LogReq, AUTO)


PB_BIND(Status, Status, AUTO)


PB_BIND(State, State, AUTO)


PB_BIND(StateLog, StateLog, 2)













