/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TAGDATA_PB_H_INCLUDED
#define PB_TAGDATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _TagType {
    TAG_UNSPECIFIED = 0,
    BITTAG = 1,
    PRESTAG = 3,
    BITTAGNG = 7,
    BITPRESTAG = 8,
    COMPASSTAG = 9,
    IMUTAG = 10
} TagType;

typedef enum _TestResult {
    TEST_UNSPECIFIED = 0,
    TEST_RUNNING = 1,
    ALL_PASSED = 2,
    RTC_FAILED = 3,
    ADXL362_FAILED = 4,
    LPS_FAILED = 5,
    EXT_FLASH_FAILED = 6,
    OPT_FAILED = 7,
    AIS2_FAILED = 8,
    MMC5633_FAILED = 9,
    /* command errors */
    SET_RTC_FAILED = 10,
    AK09940A_FAILED = 11,
    LIS2DU12_FAILED = 12,
    TEST_DEBUG_FAILED = 16, /* for debugging */
    LPS27_FAILED = 17,
    LPS22_FAILED = 18,
    AT25XE_FAILED = 19,
    MX25L_FAILED = 20,
    MX25R_FAILED = 21,
    LSM6DSV_FAILED = 22
} TestResult;

typedef enum _BitTagLogFmt {
    BITTAG_UNSPECIFIED = 0,
    BITTAG_BITPERSEC = 1,
    BITTAG_BITSPERMIN = 2,
    BITTAG_BITSPERFOURMIN = 3,
    BITTAG_BITSPERFIVEMIN = 4
} BitTagLogFmt;

typedef enum _Adxl367Channel {
    AdxlChannel_UNSPECIFIED = 0,
    AdxlChannel_xyz = 1,
    AdxlChannel_x = 2,
    AdxlChannel_y = 3,
    AdxlChannel_z = 4,
    /* should not implement other values */
    AdxlChannel_xyzt = 5,
    AdxlChannel_xt = 6,
    AdxlChannel_yt = 7,
    AdxlChannel_zt = 8,
    AdxlChannel_xyze = 9,
    AdxlChannel_xe = 10,
    AdxlChannel_ye = 11,
    AdxlChannel_ze = 12
} Adxl367Channel;

typedef enum _Lsm6dsv_ODR {
    Lsm6dsv_ODR_UNSPECIFIED = 0,
    Lsm6dsv_S50 = 50,
    Lsm6dsv_S100 = 100,
    Lsm6dsv_S200 = 200,
    Lsm6dsv_S400 = 400,
    Lsm6dsv_S800 = 800,
    Lsm6dsv_S1600 = 1600
} Lsm6dsv_ODR;

typedef enum _Lsm6dsv_ACCEL {
    Lsm6dsv_ACCEL_UNSPECIFIED = 0,
    Lsm6dsv_R2G = 1,
    Lsm6dsv_R4G = 2,
    Lsm6dsv_R8G = 3,
    Lsm6dsv_R16G = 4
} Lsm6dsv_ACCEL;

typedef enum _Lsm6dsv_GYRO {
    Lsm6dsv_GYRO_UNSPECIFIED = 0,
    Lsm6dsv_R125dps = 1,
    Lsm6dsv_R250dps = 2,
    Lsm6dsv_R500dps = 3,
    Lsm6dsv_R1000dps = 4,
    Lsm6dsv_R2000dps = 5,
    Lsm6dsv_R4000dps = 6
} Lsm6dsv_GYRO;

/* Struct definitions */
typedef struct _TagInfo {
    TagType tag_type; /* tag type (should match config) */
    /* hardware */
    char board_desc[60]; /* board description */
    char uuid[30]; /* processor unique id */
    int64_t intflashsz; /* internal flash size (bytes) */
    int64_t extflashsz; /* external flash size (bytes) */
    /* software */
    char firmware[60]; /* firmware description */
    char gitrepo[128]; /* git repo */
    char githash[30]; /* git version hash */
    char source_path[100]; /* path to source in repo */
    char build_time[30]; /* build time */
    float qtmonitor_min_version; /* minimum version of qt monitor */
    int32_t flash_blocks; /* number of flash blocks for */
    /* block erase */
    float accelconstant; /* constant for converting accel data */
    float magconstant; /* constant for converting mag data */
} TagInfo;

typedef struct _Config_Interval {
    int32_t start_epoch;
    int32_t end_epoch;
} Config_Interval;

typedef struct _Lsm6dsv {
    Lsm6dsv_ODR odr;
    Lsm6dsv_ACCEL accel_rng;
    Lsm6dsv_GYRO gyro_rng;
} Lsm6dsv;

typedef struct _Config {
    TagType tag_type;
    /* Schedule */
    bool has_active_interval;
    Config_Interval active_interval;
    pb_size_t hibernate_count;
    Config_Interval hibernate[2]; /* hibernation */
    BitTagLogFmt bittag_log; /* bittag log format */
    uint32_t period; /* period for synchronous tags */
    bool has_lsm6;
    Lsm6dsv lsm6;
    uint32_t start_delay; /* delay start in minutes */
} Config;

typedef struct _PresTagLog_PT {
    float temperature;
    float pressure;
} PresTagLog_PT;

typedef struct _BitPresTagLog_BPT {
    uint32_t activity;
    float temperature;
    float pressure;
} BitPresTagLog_BPT;

typedef PB_BYTES_ARRAY_T(120) IMUTagLogData_data_t;
typedef struct _IMUTagLogData {
    int32_t pressure_raw; /* compact pressure; hPa = raw / 16; -1 means no sample */
    int32_t mx_raw; /* compact mag; uT = raw * 0.04; all axes -1 means no sample */
    int32_t my_raw;
    int32_t mz_raw;
    IMUTagLogData_data_t data; /* packed accel, gyro data 16bit integers */
} IMUTagLogData;

typedef struct _IMUTagLog {
    int32_t epoch;
    int32_t millisecond;
    float temperature;
    pb_size_t data_count;
    IMUTagLogData data[16];
} IMUTagLog;

typedef PB_BYTES_ARRAY_T(2048) IMUTagRawLog_samples_t;
typedef struct _IMUTagRawLog {
    int32_t epoch;
    int32_t millisecond;
    float temperature;
    IMUTagRawLog_samples_t samples; /* raw DATALOG_SAMPLES * t_DataLog page image */
} IMUTagRawLog;

typedef struct _CompassTagLog_Compass {
    float activity;
    float ax;
    float ay;
    float az;
    float mx;
    float my;
    float mz;
} CompassTagLog_Compass;

typedef struct _SensorData_AccelData {
    float ax;
    float ay;
    float az;
} SensorData_AccelData;

typedef struct _SensorData_MagData {
    float mx;
    float my;
    float mz;
} SensorData_MagData;

typedef struct _SensorData {
    bool has_accel;
    SensorData_AccelData accel;
    bool has_mag;
    SensorData_MagData mag;
} SensorData;

typedef struct _CalibrationLog {
    pb_size_t data_count;
    SensorData data[25];
} CalibrationLog;

typedef struct _CalibrationConstants_MagConstants { /* M' = A(M-V) */
    float b; /* field magnetude (at calibration) */
    float v0; /* offset vector */
    float v1;
    float v2;
    float a00; /* inverted scale array */
    float a01;
    float a02;
    float a10;
    float a11;
    float a12;
    float a20;
    float a21;
    float a22;
} CalibrationConstants_MagConstants;

typedef struct _CalibrationConstants {
    int32_t timestamp;
    bool has_magnetometer;
    CalibrationConstants_MagConstants magnetometer;
} CalibrationConstants;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _TagType_MIN TAG_UNSPECIFIED
#define _TagType_MAX IMUTAG
#define _TagType_ARRAYSIZE ((TagType)(IMUTAG+1))
#define TagType_TAG_UNSPECIFIED TAG_UNSPECIFIED
#define TagType_BITTAG BITTAG
#define TagType_PRESTAG PRESTAG
#define TagType_BITTAGNG BITTAGNG
#define TagType_BITPRESTAG BITPRESTAG
#define TagType_COMPASSTAG COMPASSTAG
#define TagType_IMUTAG IMUTAG

#define _TestResult_MIN TEST_UNSPECIFIED
#define _TestResult_MAX LSM6DSV_FAILED
#define _TestResult_ARRAYSIZE ((TestResult)(LSM6DSV_FAILED+1))
#define TestResult_TEST_UNSPECIFIED TEST_UNSPECIFIED
#define TestResult_TEST_RUNNING TEST_RUNNING
#define TestResult_ALL_PASSED ALL_PASSED
#define TestResult_RTC_FAILED RTC_FAILED
#define TestResult_ADXL362_FAILED ADXL362_FAILED
#define TestResult_LPS_FAILED LPS_FAILED
#define TestResult_EXT_FLASH_FAILED EXT_FLASH_FAILED
#define TestResult_OPT_FAILED OPT_FAILED
#define TestResult_AIS2_FAILED AIS2_FAILED
#define TestResult_MMC5633_FAILED MMC5633_FAILED
#define TestResult_SET_RTC_FAILED SET_RTC_FAILED
#define TestResult_AK09940A_FAILED AK09940A_FAILED
#define TestResult_LIS2DU12_FAILED LIS2DU12_FAILED
#define TestResult_TEST_DEBUG_FAILED TEST_DEBUG_FAILED
#define TestResult_LPS27_FAILED LPS27_FAILED
#define TestResult_LPS22_FAILED LPS22_FAILED
#define TestResult_AT25XE_FAILED AT25XE_FAILED
#define TestResult_MX25L_FAILED MX25L_FAILED
#define TestResult_MX25R_FAILED MX25R_FAILED
#define TestResult_LSM6DSV_FAILED LSM6DSV_FAILED

#define _BitTagLogFmt_MIN BITTAG_UNSPECIFIED
#define _BitTagLogFmt_MAX BITTAG_BITSPERFIVEMIN
#define _BitTagLogFmt_ARRAYSIZE ((BitTagLogFmt)(BITTAG_BITSPERFIVEMIN+1))
#define BitTagLogFmt_BITTAG_UNSPECIFIED BITTAG_UNSPECIFIED
#define BitTagLogFmt_BITTAG_BITPERSEC BITTAG_BITPERSEC
#define BitTagLogFmt_BITTAG_BITSPERMIN BITTAG_BITSPERMIN
#define BitTagLogFmt_BITTAG_BITSPERFOURMIN BITTAG_BITSPERFOURMIN
#define BitTagLogFmt_BITTAG_BITSPERFIVEMIN BITTAG_BITSPERFIVEMIN

#define _Adxl367Channel_MIN AdxlChannel_UNSPECIFIED
#define _Adxl367Channel_MAX AdxlChannel_ze
#define _Adxl367Channel_ARRAYSIZE ((Adxl367Channel)(AdxlChannel_ze+1))
#define Adxl367Channel_AdxlChannel_UNSPECIFIED AdxlChannel_UNSPECIFIED
#define Adxl367Channel_AdxlChannel_xyz AdxlChannel_xyz
#define Adxl367Channel_AdxlChannel_x AdxlChannel_x
#define Adxl367Channel_AdxlChannel_y AdxlChannel_y
#define Adxl367Channel_AdxlChannel_z AdxlChannel_z
#define Adxl367Channel_AdxlChannel_xyzt AdxlChannel_xyzt
#define Adxl367Channel_AdxlChannel_xt AdxlChannel_xt
#define Adxl367Channel_AdxlChannel_yt AdxlChannel_yt
#define Adxl367Channel_AdxlChannel_zt AdxlChannel_zt
#define Adxl367Channel_AdxlChannel_xyze AdxlChannel_xyze
#define Adxl367Channel_AdxlChannel_xe AdxlChannel_xe
#define Adxl367Channel_AdxlChannel_ye AdxlChannel_ye
#define Adxl367Channel_AdxlChannel_ze AdxlChannel_ze

#define _Lsm6dsv_ODR_MIN Lsm6dsv_ODR_UNSPECIFIED
#define _Lsm6dsv_ODR_MAX Lsm6dsv_S1600
#define _Lsm6dsv_ODR_ARRAYSIZE ((Lsm6dsv_ODR)(Lsm6dsv_S1600+1))
#define Lsm6dsv_ODR_ODR_UNSPECIFIED Lsm6dsv_ODR_UNSPECIFIED
#define Lsm6dsv_ODR_S50 Lsm6dsv_S50
#define Lsm6dsv_ODR_S100 Lsm6dsv_S100
#define Lsm6dsv_ODR_S200 Lsm6dsv_S200
#define Lsm6dsv_ODR_S400 Lsm6dsv_S400
#define Lsm6dsv_ODR_S800 Lsm6dsv_S800
#define Lsm6dsv_ODR_S1600 Lsm6dsv_S1600

#define _Lsm6dsv_ACCEL_MIN Lsm6dsv_ACCEL_UNSPECIFIED
#define _Lsm6dsv_ACCEL_MAX Lsm6dsv_R16G
#define _Lsm6dsv_ACCEL_ARRAYSIZE ((Lsm6dsv_ACCEL)(Lsm6dsv_R16G+1))
#define Lsm6dsv_ACCEL_ACCEL_UNSPECIFIED Lsm6dsv_ACCEL_UNSPECIFIED
#define Lsm6dsv_ACCEL_R2G Lsm6dsv_R2G
#define Lsm6dsv_ACCEL_R4G Lsm6dsv_R4G
#define Lsm6dsv_ACCEL_R8G Lsm6dsv_R8G
#define Lsm6dsv_ACCEL_R16G Lsm6dsv_R16G

#define _Lsm6dsv_GYRO_MIN Lsm6dsv_GYRO_UNSPECIFIED
#define _Lsm6dsv_GYRO_MAX Lsm6dsv_R4000dps
#define _Lsm6dsv_GYRO_ARRAYSIZE ((Lsm6dsv_GYRO)(Lsm6dsv_R4000dps+1))
#define Lsm6dsv_GYRO_GYRO_UNSPECIFIED Lsm6dsv_GYRO_UNSPECIFIED
#define Lsm6dsv_GYRO_R125dps Lsm6dsv_R125dps
#define Lsm6dsv_GYRO_R250dps Lsm6dsv_R250dps
#define Lsm6dsv_GYRO_R500dps Lsm6dsv_R500dps
#define Lsm6dsv_GYRO_R1000dps Lsm6dsv_R1000dps
#define Lsm6dsv_GYRO_R2000dps Lsm6dsv_R2000dps
#define Lsm6dsv_GYRO_R4000dps Lsm6dsv_R4000dps

#define TagInfo_tag_type_ENUMTYPE TagType

#define Config_tag_type_ENUMTYPE TagType
#define Config_bittag_log_ENUMTYPE BitTagLogFmt


#define Lsm6dsv_odr_ENUMTYPE Lsm6dsv_ODR
#define Lsm6dsv_accel_rng_ENUMTYPE Lsm6dsv_ACCEL
#define Lsm6dsv_gyro_rng_ENUMTYPE Lsm6dsv_GYRO














/* Initializer values for message structs */
#define TagInfo_init_default                     {_TagType_MIN, "", "", 0, 0, "", "", "", "", "", 0, 0, 0, 0}
#define Config_init_default                      {_TagType_MIN, false, Config_Interval_init_default, 0, {Config_Interval_init_default, Config_Interval_init_default}, _BitTagLogFmt_MIN, 0, false, Lsm6dsv_init_default, 0}
#define Config_Interval_init_default             {0, 0}
#define Lsm6dsv_init_default                     {_Lsm6dsv_ODR_MIN, _Lsm6dsv_ACCEL_MIN, _Lsm6dsv_GYRO_MIN}
#define PresTagLog_PT_init_default               {0, 0}
#define BitPresTagLog_BPT_init_default           {0, 0, 0}
#define IMUTagLogData_init_default               {0, 0, 0, 0, {0, {0}}}
#define IMUTagLog_init_default                   {0, 0, 0, 0, {IMUTagLogData_init_default, IMUTagLogData_init_default, IMUTagLogData_init_default, IMUTagLogData_init_default, IMUTagLogData_init_default, IMUTagLogData_init_default, IMUTagLogData_init_default, IMUTagLogData_init_default, IMUTagLogData_init_default, IMUTagLogData_init_default, IMUTagLogData_init_default, IMUTagLogData_init_default, IMUTagLogData_init_default, IMUTagLogData_init_default, IMUTagLogData_init_default, IMUTagLogData_init_default}}
#define IMUTagRawLog_init_default                {0, 0, 0, {0, {0}}}
#define CompassTagLog_Compass_init_default       {0, 0, 0, 0, 0, 0, 0}
#define SensorData_init_default                  {false, SensorData_AccelData_init_default, false, SensorData_MagData_init_default}
#define SensorData_AccelData_init_default        {0, 0, 0}
#define SensorData_MagData_init_default          {0, 0, 0}
#define CalibrationLog_init_default              {0, {SensorData_init_default, SensorData_init_default, SensorData_init_default, SensorData_init_default, SensorData_init_default, SensorData_init_default, SensorData_init_default, SensorData_init_default, SensorData_init_default, SensorData_init_default, SensorData_init_default, SensorData_init_default, SensorData_init_default, SensorData_init_default, SensorData_init_default, SensorData_init_default, SensorData_init_default, SensorData_init_default, SensorData_init_default, SensorData_init_default, SensorData_init_default, SensorData_init_default, SensorData_init_default, SensorData_init_default, SensorData_init_default}}
#define CalibrationConstants_init_default        {0, false, CalibrationConstants_MagConstants_init_default}
#define CalibrationConstants_MagConstants_init_default {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define TagInfo_init_zero                        {_TagType_MIN, "", "", 0, 0, "", "", "", "", "", 0, 0, 0, 0}
#define Config_init_zero                         {_TagType_MIN, false, Config_Interval_init_zero, 0, {Config_Interval_init_zero, Config_Interval_init_zero}, _BitTagLogFmt_MIN, 0, false, Lsm6dsv_init_zero, 0}
#define Config_Interval_init_zero                {0, 0}
#define Lsm6dsv_init_zero                        {_Lsm6dsv_ODR_MIN, _Lsm6dsv_ACCEL_MIN, _Lsm6dsv_GYRO_MIN}
#define PresTagLog_PT_init_zero                  {0, 0}
#define BitPresTagLog_BPT_init_zero              {0, 0, 0}
#define IMUTagLogData_init_zero                  {0, 0, 0, 0, {0, {0}}}
#define IMUTagLog_init_zero                      {0, 0, 0, 0, {IMUTagLogData_init_zero, IMUTagLogData_init_zero, IMUTagLogData_init_zero, IMUTagLogData_init_zero, IMUTagLogData_init_zero, IMUTagLogData_init_zero, IMUTagLogData_init_zero, IMUTagLogData_init_zero, IMUTagLogData_init_zero, IMUTagLogData_init_zero, IMUTagLogData_init_zero, IMUTagLogData_init_zero, IMUTagLogData_init_zero, IMUTagLogData_init_zero, IMUTagLogData_init_zero, IMUTagLogData_init_zero}}
#define IMUTagRawLog_init_zero                   {0, 0, 0, {0, {0}}}
#define CompassTagLog_Compass_init_zero          {0, 0, 0, 0, 0, 0, 0}
#define SensorData_init_zero                     {false, SensorData_AccelData_init_zero, false, SensorData_MagData_init_zero}
#define SensorData_AccelData_init_zero           {0, 0, 0}
#define SensorData_MagData_init_zero             {0, 0, 0}
#define CalibrationLog_init_zero                 {0, {SensorData_init_zero, SensorData_init_zero, SensorData_init_zero, SensorData_init_zero, SensorData_init_zero, SensorData_init_zero, SensorData_init_zero, SensorData_init_zero, SensorData_init_zero, SensorData_init_zero, SensorData_init_zero, SensorData_init_zero, SensorData_init_zero, SensorData_init_zero, SensorData_init_zero, SensorData_init_zero, SensorData_init_zero, SensorData_init_zero, SensorData_init_zero, SensorData_init_zero, SensorData_init_zero, SensorData_init_zero, SensorData_init_zero, SensorData_init_zero, SensorData_init_zero}}
#define CalibrationConstants_init_zero           {0, false, CalibrationConstants_MagConstants_init_zero}
#define CalibrationConstants_MagConstants_init_zero {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define TagInfo_tag_type_tag                     1
#define TagInfo_board_desc_tag                   2
#define TagInfo_uuid_tag                         3
#define TagInfo_intflashsz_tag                   4
#define TagInfo_extflashsz_tag                   5
#define TagInfo_firmware_tag                     6
#define TagInfo_gitrepo_tag                      7
#define TagInfo_githash_tag                      8
#define TagInfo_source_path_tag                  9
#define TagInfo_build_time_tag                   10
#define TagInfo_qtmonitor_min_version_tag        11
#define TagInfo_flash_blocks_tag                 12
#define TagInfo_accelconstant_tag                13
#define TagInfo_magconstant_tag                  14
#define Config_Interval_start_epoch_tag          1
#define Config_Interval_end_epoch_tag            2
#define Lsm6dsv_odr_tag                          1
#define Lsm6dsv_accel_rng_tag                    2
#define Lsm6dsv_gyro_rng_tag                     3
#define Config_tag_type_tag                      1
#define Config_active_interval_tag               2
#define Config_hibernate_tag                     3
#define Config_bittag_log_tag                    4
#define Config_period_tag                        7
#define Config_lsm6_tag                          8
#define Config_start_delay_tag                   9
#define PresTagLog_PT_temperature_tag            1
#define PresTagLog_PT_pressure_tag               2
#define BitPresTagLog_BPT_activity_tag           1
#define BitPresTagLog_BPT_temperature_tag        2
#define BitPresTagLog_BPT_pressure_tag           3
#define IMUTagLogData_pressure_raw_tag           1
#define IMUTagLogData_mx_raw_tag                 2
#define IMUTagLogData_my_raw_tag                 3
#define IMUTagLogData_mz_raw_tag                 4
#define IMUTagLogData_data_tag                   5
#define IMUTagLog_epoch_tag                      1
#define IMUTagLog_millisecond_tag                2
#define IMUTagLog_temperature_tag                3
#define IMUTagLog_data_tag                       4
#define IMUTagRawLog_epoch_tag                   1
#define IMUTagRawLog_millisecond_tag             2
#define IMUTagRawLog_temperature_tag             3
#define IMUTagRawLog_samples_tag                 4
#define CompassTagLog_Compass_activity_tag       1
#define CompassTagLog_Compass_ax_tag             2
#define CompassTagLog_Compass_ay_tag             3
#define CompassTagLog_Compass_az_tag             4
#define CompassTagLog_Compass_mx_tag             5
#define CompassTagLog_Compass_my_tag             6
#define CompassTagLog_Compass_mz_tag             7
#define SensorData_AccelData_ax_tag              1
#define SensorData_AccelData_ay_tag              2
#define SensorData_AccelData_az_tag              3
#define SensorData_MagData_mx_tag                1
#define SensorData_MagData_my_tag                2
#define SensorData_MagData_mz_tag                3
#define SensorData_accel_tag                     1
#define SensorData_mag_tag                       2
#define CalibrationLog_data_tag                  1
#define CalibrationConstants_MagConstants_b_tag  1
#define CalibrationConstants_MagConstants_v0_tag 2
#define CalibrationConstants_MagConstants_v1_tag 3
#define CalibrationConstants_MagConstants_v2_tag 4
#define CalibrationConstants_MagConstants_a00_tag 5
#define CalibrationConstants_MagConstants_a01_tag 6
#define CalibrationConstants_MagConstants_a02_tag 7
#define CalibrationConstants_MagConstants_a10_tag 8
#define CalibrationConstants_MagConstants_a11_tag 9
#define CalibrationConstants_MagConstants_a12_tag 10
#define CalibrationConstants_MagConstants_a20_tag 11
#define CalibrationConstants_MagConstants_a21_tag 12
#define CalibrationConstants_MagConstants_a22_tag 13
#define CalibrationConstants_timestamp_tag       1
#define CalibrationConstants_magnetometer_tag    2

/* Struct field encoding specification for nanopb */
#define TagInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    tag_type,          1) \
X(a, STATIC,   SINGULAR, STRING,   board_desc,        2) \
X(a, STATIC,   SINGULAR, STRING,   uuid,              3) \
X(a, STATIC,   SINGULAR, INT64,    intflashsz,        4) \
X(a, STATIC,   SINGULAR, INT64,    extflashsz,        5) \
X(a, STATIC,   SINGULAR, STRING,   firmware,          6) \
X(a, STATIC,   SINGULAR, STRING,   gitrepo,           7) \
X(a, STATIC,   SINGULAR, STRING,   githash,           8) \
X(a, STATIC,   SINGULAR, STRING,   source_path,       9) \
X(a, STATIC,   SINGULAR, STRING,   build_time,       10) \
X(a, STATIC,   SINGULAR, FLOAT,    qtmonitor_min_version,  11) \
X(a, STATIC,   SINGULAR, INT32,    flash_blocks,     12) \
X(a, STATIC,   SINGULAR, FLOAT,    accelconstant,    13) \
X(a, STATIC,   SINGULAR, FLOAT,    magconstant,      14)
#define TagInfo_CALLBACK NULL
#define TagInfo_DEFAULT NULL

#define Config_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    tag_type,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  active_interval,   2) \
X(a, STATIC,   REPEATED, MESSAGE,  hibernate,         3) \
X(a, STATIC,   SINGULAR, UENUM,    bittag_log,        4) \
X(a, STATIC,   SINGULAR, UINT32,   period,            7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  lsm6,              8) \
X(a, STATIC,   SINGULAR, UINT32,   start_delay,       9)
#define Config_CALLBACK NULL
#define Config_DEFAULT NULL
#define Config_active_interval_MSGTYPE Config_Interval
#define Config_hibernate_MSGTYPE Config_Interval
#define Config_lsm6_MSGTYPE Lsm6dsv

#define Config_Interval_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    start_epoch,       1) \
X(a, STATIC,   SINGULAR, INT32,    end_epoch,         2)
#define Config_Interval_CALLBACK NULL
#define Config_Interval_DEFAULT NULL

#define Lsm6dsv_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    odr,               1) \
X(a, STATIC,   SINGULAR, UENUM,    accel_rng,         2) \
X(a, STATIC,   SINGULAR, UENUM,    gyro_rng,          3)
#define Lsm6dsv_CALLBACK NULL
#define Lsm6dsv_DEFAULT NULL

#define PresTagLog_PT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       1) \
X(a, STATIC,   SINGULAR, FLOAT,    pressure,          2)
#define PresTagLog_PT_CALLBACK NULL
#define PresTagLog_PT_DEFAULT NULL

#define BitPresTagLog_BPT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED32,  activity,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    pressure,          3)
#define BitPresTagLog_BPT_CALLBACK NULL
#define BitPresTagLog_BPT_DEFAULT NULL

#define IMUTagLogData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    pressure_raw,      1) \
X(a, STATIC,   SINGULAR, INT32,    mx_raw,            2) \
X(a, STATIC,   SINGULAR, INT32,    my_raw,            3) \
X(a, STATIC,   SINGULAR, INT32,    mz_raw,            4) \
X(a, STATIC,   SINGULAR, BYTES,    data,              5)
#define IMUTagLogData_CALLBACK NULL
#define IMUTagLogData_DEFAULT NULL

#define IMUTagLog_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    epoch,             1) \
X(a, STATIC,   SINGULAR, INT32,    millisecond,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       3) \
X(a, STATIC,   REPEATED, MESSAGE,  data,              4)
#define IMUTagLog_CALLBACK NULL
#define IMUTagLog_DEFAULT NULL
#define IMUTagLog_data_MSGTYPE IMUTagLogData

#define IMUTagRawLog_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    epoch,             1) \
X(a, STATIC,   SINGULAR, INT32,    millisecond,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       3) \
X(a, STATIC,   SINGULAR, BYTES,    samples,           4)
#define IMUTagRawLog_CALLBACK NULL
#define IMUTagRawLog_DEFAULT NULL

#define CompassTagLog_Compass_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    activity,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    ax,                2) \
X(a, STATIC,   SINGULAR, FLOAT,    ay,                3) \
X(a, STATIC,   SINGULAR, FLOAT,    az,                4) \
X(a, STATIC,   SINGULAR, FLOAT,    mx,                5) \
X(a, STATIC,   SINGULAR, FLOAT,    my,                6) \
X(a, STATIC,   SINGULAR, FLOAT,    mz,                7)
#define CompassTagLog_Compass_CALLBACK NULL
#define CompassTagLog_Compass_DEFAULT NULL

#define SensorData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  accel,             1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  mag,               2)
#define SensorData_CALLBACK NULL
#define SensorData_DEFAULT NULL
#define SensorData_accel_MSGTYPE SensorData_AccelData
#define SensorData_mag_MSGTYPE SensorData_MagData

#define SensorData_AccelData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    ax,                1) \
X(a, STATIC,   SINGULAR, FLOAT,    ay,                2) \
X(a, STATIC,   SINGULAR, FLOAT,    az,                3)
#define SensorData_AccelData_CALLBACK NULL
#define SensorData_AccelData_DEFAULT NULL

#define SensorData_MagData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    mx,                1) \
X(a, STATIC,   SINGULAR, FLOAT,    my,                2) \
X(a, STATIC,   SINGULAR, FLOAT,    mz,                3)
#define SensorData_MagData_CALLBACK NULL
#define SensorData_MagData_DEFAULT NULL

#define CalibrationLog_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  data,              1)
#define CalibrationLog_CALLBACK NULL
#define CalibrationLog_DEFAULT NULL
#define CalibrationLog_data_MSGTYPE SensorData

#define CalibrationConstants_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SFIXED32, timestamp,         1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  magnetometer,      2)
#define CalibrationConstants_CALLBACK NULL
#define CalibrationConstants_DEFAULT NULL
#define CalibrationConstants_magnetometer_MSGTYPE CalibrationConstants_MagConstants

#define CalibrationConstants_MagConstants_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    b,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    v0,                2) \
X(a, STATIC,   SINGULAR, FLOAT,    v1,                3) \
X(a, STATIC,   SINGULAR, FLOAT,    v2,                4) \
X(a, STATIC,   SINGULAR, FLOAT,    a00,               5) \
X(a, STATIC,   SINGULAR, FLOAT,    a01,               6) \
X(a, STATIC,   SINGULAR, FLOAT,    a02,               7) \
X(a, STATIC,   SINGULAR, FLOAT,    a10,               8) \
X(a, STATIC,   SINGULAR, FLOAT,    a11,               9) \
X(a, STATIC,   SINGULAR, FLOAT,    a12,              10) \
X(a, STATIC,   SINGULAR, FLOAT,    a20,              11) \
X(a, STATIC,   SINGULAR, FLOAT,    a21,              12) \
X(a, STATIC,   SINGULAR, FLOAT,    a22,              13)
#define CalibrationConstants_MagConstants_CALLBACK NULL
#define CalibrationConstants_MagConstants_DEFAULT NULL

extern const pb_msgdesc_t TagInfo_msg;
extern const pb_msgdesc_t Config_msg;
extern const pb_msgdesc_t Config_Interval_msg;
extern const pb_msgdesc_t Lsm6dsv_msg;
extern const pb_msgdesc_t PresTagLog_PT_msg;
extern const pb_msgdesc_t BitPresTagLog_BPT_msg;
extern const pb_msgdesc_t IMUTagLogData_msg;
extern const pb_msgdesc_t IMUTagLog_msg;
extern const pb_msgdesc_t IMUTagRawLog_msg;
extern const pb_msgdesc_t CompassTagLog_Compass_msg;
extern const pb_msgdesc_t SensorData_msg;
extern const pb_msgdesc_t SensorData_AccelData_msg;
extern const pb_msgdesc_t SensorData_MagData_msg;
extern const pb_msgdesc_t CalibrationLog_msg;
extern const pb_msgdesc_t CalibrationConstants_msg;
extern const pb_msgdesc_t CalibrationConstants_MagConstants_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define TagInfo_fields &TagInfo_msg
#define Config_fields &Config_msg
#define Config_Interval_fields &Config_Interval_msg
#define Lsm6dsv_fields &Lsm6dsv_msg
#define PresTagLog_PT_fields &PresTagLog_PT_msg
#define BitPresTagLog_BPT_fields &BitPresTagLog_BPT_msg
#define IMUTagLogData_fields &IMUTagLogData_msg
#define IMUTagLog_fields &IMUTagLog_msg
#define IMUTagRawLog_fields &IMUTagRawLog_msg
#define CompassTagLog_Compass_fields &CompassTagLog_Compass_msg
#define SensorData_fields &SensorData_msg
#define SensorData_AccelData_fields &SensorData_AccelData_msg
#define SensorData_MagData_fields &SensorData_MagData_msg
#define CalibrationLog_fields &CalibrationLog_msg
#define CalibrationConstants_fields &CalibrationConstants_msg
#define CalibrationConstants_MagConstants_fields &CalibrationConstants_MagConstants_msg

/* Maximum encoded size of messages (where known) */
#define BitPresTagLog_BPT_size                   15
#define CalibrationConstants_MagConstants_size   65
#define CalibrationConstants_size                72
#define CalibrationLog_size                      900
#define CompassTagLog_Compass_size               35
#define Config_Interval_size                     22
#define Config_size                              97
#define IMUTagLogData_size                       166
#define IMUTagLog_size                           2731
#define IMUTagRawLog_size                        2078
#define Lsm6dsv_size                             7
#define PresTagLog_PT_size                       10
#define SensorData_AccelData_size                15
#define SensorData_MagData_size                  15
#define SensorData_size                          34
#define TAGDATA_PB_H_MAX_SIZE                    IMUTagLog_size
#define TagInfo_size                             496

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
