/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "tagdata.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(TagInfo, TagInfo, 2)


PB_BIND(Config, Config, AUTO)


PB_BIND(Config_Interval, Config_Interval, AUTO)


PB_BIND(Lsm6dsv, Lsm6dsv, AUTO)


PB_BIND(PresTagLog_PT, PresTagLog_PT, AUTO)


PB_BIND(BitPresTagLog_BPT, BitPresTagLog_BPT, AUTO)


PB_BIND(IMUTagLogData, IMUTagLogData, AUTO)


PB_BIND(IMUTagLog, IMUTagLog, 2)


PB_BIND(IMUTagRawLog, IMUTagRawLog, 2)


PB_BIND(CompassTagLog_Compass, CompassTagLog_Compass, AUTO)


PB_BIND(SensorData, SensorData, AUTO)


PB_BIND(SensorData_AccelData, SensorData_AccelData, AUTO)


PB_BIND(SensorData_MagData, SensorData_MagData, AUTO)


PB_BIND(CalibrationLog, CalibrationLog, 2)


PB_BIND(CalibrationConstants, CalibrationConstants, AUTO)


PB_BIND(CalibrationConstants_MagConstants, CalibrationConstants_MagConstants, AUTO)

















