include_guard(GLOBAL)

function(install_build_report)
    set(options)
    set(one_value_args DESTINATION)
    set(multi_value_args TARGETS)
    cmake_parse_arguments(BUILD_REPORT
        "${options}"
        "${one_value_args}"
        "${multi_value_args}"
        ${ARGN})

    if(NOT BUILD_REPORT_DESTINATION)
        set(BUILD_REPORT_DESTINATION ".")
    endif()

    find_package(Git QUIET)
    find_package(Protobuf QUIET)
    find_package(SQLite3 QUIET)
    find_package(Qt6Core QUIET)
    find_package(PkgConfig QUIET)
    if(PkgConfig_FOUND)
        pkg_check_modules(BUILD_REPORT_LIBUSB QUIET libusb-1.0)
    endif()

    set(_build_report_target_names "")
    foreach(_target IN LISTS BUILD_REPORT_TARGETS)
        if(TARGET ${_target})
            get_target_property(_target_output_name ${_target} OUTPUT_NAME)
            if(NOT _target_output_name)
                set(_target_output_name ${_target})
            endif()
            list(APPEND _build_report_target_names "${_target_output_name}")
        endif()
    endforeach()
    if(_build_report_target_names)
        list(REMOVE_DUPLICATES _build_report_target_names)
    endif()

    set(BUILD_REPORT_PACKAGE_NAME "${CPACK_PACKAGE_NAME}")
    set(BUILD_REPORT_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION}")
    set(BUILD_REPORT_PROJECT_NAME "${CMAKE_PROJECT_NAME}")
    set(BUILD_REPORT_PROJECT_VERSION "${CMAKE_PROJECT_VERSION}")
    set(BUILD_REPORT_SOURCE_DIR "${CMAKE_SOURCE_DIR}")
    set(BUILD_REPORT_BINARY_DIR "${CMAKE_BINARY_DIR}")
    set(BUILD_REPORT_INSTALL_DESTINATION "${BUILD_REPORT_DESTINATION}")
    set(BUILD_REPORT_TARGET_NAMES "${_build_report_target_names}")
    set(BUILD_REPORT_CMAKE_VERSION "${CMAKE_VERSION}")
    set(BUILD_REPORT_GENERATOR "${CMAKE_GENERATOR}")
    set(BUILD_REPORT_SYSTEM_NAME "${CMAKE_SYSTEM_NAME}")
    set(BUILD_REPORT_SYSTEM_VERSION "${CMAKE_SYSTEM_VERSION}")
    set(BUILD_REPORT_SYSTEM_PROCESSOR "${CMAKE_SYSTEM_PROCESSOR}")
    set(BUILD_REPORT_OSX_DEPLOYMENT_TARGET "${CMAKE_OSX_DEPLOYMENT_TARGET}")
    set(BUILD_REPORT_OSX_SYSROOT "${CMAKE_OSX_SYSROOT}")
    set(BUILD_REPORT_C_COMPILER "${CMAKE_C_COMPILER}")
    set(BUILD_REPORT_C_COMPILER_ID "${CMAKE_C_COMPILER_ID}")
    set(BUILD_REPORT_C_COMPILER_VERSION "${CMAKE_C_COMPILER_VERSION}")
    set(BUILD_REPORT_CXX_COMPILER "${CMAKE_CXX_COMPILER}")
    set(BUILD_REPORT_CXX_COMPILER_ID "${CMAKE_CXX_COMPILER_ID}")
    set(BUILD_REPORT_CXX_COMPILER_VERSION "${CMAKE_CXX_COMPILER_VERSION}")
    set(BUILD_REPORT_GIT_EXECUTABLE "${GIT_EXECUTABLE}")
    set(BUILD_REPORT_QT_VERSION "${Qt6Core_VERSION}")
    set(BUILD_REPORT_QT_DIR "${Qt6Core_DIR}")
    set(BUILD_REPORT_PROTOBUF_VERSION "${Protobuf_VERSION}")
    set(BUILD_REPORT_PROTOBUF_INCLUDE_DIRS "${Protobuf_INCLUDE_DIRS}")
    set(BUILD_REPORT_SQLITE3_VERSION "${SQLite3_VERSION}")
    set(BUILD_REPORT_SQLITE3_INCLUDE_DIRS "${SQLite3_INCLUDE_DIRS}")
    set(BUILD_REPORT_LIBUSB_VERSION "${BUILD_REPORT_LIBUSB_VERSION}")
    set(BUILD_REPORT_LIBUSB_INCLUDE_DIRS "${BUILD_REPORT_LIBUSB_INCLUDE_DIRS}")
    set(BUILD_REPORT_VCPKG_INSTALLED_DIR "${VCPKG_INSTALLED_DIR}")
    set(BUILD_REPORT_VCPKG_TARGET_TRIPLET "${VCPKG_TARGET_TRIPLET}")

    configure_file(
        "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/GenerateBuildReport.cmake.in"
        "${CMAKE_CURRENT_BINARY_DIR}/GenerateBuildReport.cmake"
        @ONLY)

    install(SCRIPT "${CMAKE_CURRENT_BINARY_DIR}/GenerateBuildReport.cmake")
endfunction()
