#ifndef SENSORVIZ_SENSORSTREAM_H
#define SENSORVIZ_SENSORSTREAM_H

#include <QColor>
#include <QMap>
#include <QString>
#include <QVector>

#include "compass_types.h"

// sensorstream.h defines the normalized data model used everywhere after the
// SQLite loader finishes. The rest of sensorViz should work with these types
// rather than with database table names. New stored streams are described by
// the SQLite streams metadata written by tagcore.

// Which side of the plot a stream's value axis should occupy. Profiles use
// this to keep diagnostics such as voltage/temperature on the right while most
// sensor data stays on the left.
enum class SensorAxisSide
{
    Left,
    Right,
};

// Optional fixed y-axis range for a stream. When enabled, plotting.cpp uses
// this as the default range until the user sets a custom range.
struct SensorAxisRange
{
    bool enabled = false;
    double lower = 0.0;
    double upper = 0.0;
};

// sensorViz has two layers of data:
//
// 1. SqliteLoader reads the database streams metadata and the tables it
//    references.
// 2. The UI consumes normalized SensorStream and SensorRecordSet objects and
//    does not care which tag type produced them.
//
// A SensorStream is therefore the main handoff type between file loading and
// plotting. When adding a new sensor, prefer converting its table into a new
// SensorStream id instead of adding tag-specific checks to MainWindow.
struct SensorStream
{
    // Stable programmatic id used by menu actions, transforms, and saved ranges.
    // Examples: "pressure", "activity", "altitude", "activity_lowpass".
    QString id;

    // User-facing axis/menu label and units. Units may be empty.
    QString label;
    QString units;

    // Epoch seconds and corresponding values. Vectors are kept parallel.
    QVector<double> time;
    QVector<double> value;

    // Plot styling. Derived streams are generated by sensorViz rather than read
    // directly from the database; they are drawn slightly heavier.
    QColor color;
    bool derived = false;

    // Initial View menu state after a log is loaded. Runtime visibility still
    // lives in the QAction so top-level and context menus stay synchronized.
    bool defaultVisible = true;

    // Stable plotting defaults. These keep diagnostic streams such as voltage
    // and core temperature on the right and let database metadata set sane
    // default ranges, while still allowing user-configured ranges to override
    // them.
    SensorAxisSide axisSide = SensorAxisSide::Left;
    SensorAxisRange axisRange;
};

// Multi-column sensor data that is not itself a single plottable y-axis series.
// Compass data is the motivating future case: one Compass table has accel and
// magnetometer columns, and later transforms can turn those columns into scalar
// streams such as heading, pitch, roll, and acceleration magnitude.
struct SensorRecordSet
{
    // Stable id used by transform code, for example "compass_raw".
    QString id;

    // Human-readable label shown in File Info.
    QString label;

    // Epoch seconds shared by all columns.
    QVector<double> time;

    // Column name to values. Transform code owns interpretation of each column.
    QMap<QString, QVector<double>> columns;
};

// Loaded SQLite log plus the streams sensorViz knows how to display. Tag type
// is metadata for the File Info pane; UI features are driven by actual streams.
struct SensorLog
{
    // Original database path, used for File Info and default directory state.
    QString path;

    // Metadata read from the Info table. Feature availability is still driven
    // by actual streams/record sets, not this string.
    QString tagType;

    // Human-readable tag/log family name selected from Info.tagtype.
    QString profileName;

    // Raw info table values, with large opaque config/info blobs filtered out
    // only when the File Info tab is rendered.
    QMap<QString, QString> info;

    // Scalar series available to the View menu and plot.
    QVector<SensorStream> streams;

    // Multi-column tables available to transform code.
    QVector<SensorRecordSet> recordSets;

    // CompassTag logs carry calibration constants in a separate table. Keep
    // them typed here rather than hiding them in the generic info map so the
    // next layer can derive heading/pitch/roll streams without reparsing JSON.
    bool hasCompassCalibration = false;
    qint64 compassCalibrationEpoch = 0;
    CompassCalibration compassCalibration;
    QString compassCalibrationWarning;
};

#endif
